### PR TITLE
chore(deps): update remote-state version

### PR DESCRIPTION
**Pull request by mtweeman**
## what
- remote state version update

## why
- current version is not the latest one with some compatibility problems resolved

## references
N/A

### CODE REVIEW

**Comment by goruha** [comment]
@mtweeman, thanks for your contribution.
we will merge this PR next week

**Comment by mtweeman** [comment]
Hey @goruha, I got notification of it being closed, but I don't see it was merged. Did sth went wrong?

**Comment by goruha** [comment]
@mtweeman I'm sorry for that.
I re-run the migration script 2 days ago to preserve the git history from the previous repo.
All PRs were closed automatically due to the commits tree force change. 
Could you pls reopen the PR?

**Comment by mtweeman** [comment]
@goruha, no worries, I heard during office hours that it was complex. I wasn't able to reopen previous PR, so I already created the new one (#5).

**Pull request closed without merging**
